name: OOXMLValidator Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  AZURE_FUNCTIONAPP_NAME: OOXMLValidator  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'              # set this to the dotnet version to use

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
